services:
  # add noop profiles so we don't run dev instances by accident when running tests
  database:
    profiles: ["noop"]
  drupal:
    profiles: ["noop"]

  # overrides
  spatial:
      links:
        - database-test

networks:
  weather.gov:
