runs:
  using: composite
  steps:
    - name: database dump cache
      uses: actions/cache@v4
      id: db-cache
      with:
        key: drupal-database-${{ hashFiles('web/config/**/*.yml', 'web/scs-export/**/*', 'web/modules/weather_i18n/translations/*.po', 'spatial/**/*.js') }}
        path: weathergov.sql

    - name: setup image cacheing
      if: steps.db-cache.outputs.cache-hit != 'true'
      uses: actions/cache@v4
      with:
        key: drupal-image-${{ hashFiles('composer.lock','web/sites/example.settings.dev.php','Dockerfile.dev') }}
        path: /tmp/image.tar

    - name: cache spatial data
      if: steps.db-cache.outputs.cache-hit != 'true'
      uses: actions/cache@v4
      with:
        key: spatial-data-05mr24
        path: |
          spatial-data/c_05mr24.zip
          spatial-data/s_05mr24.zip

    - name: start the site
      if: steps.db-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        docker load --input /tmp/image.tar
        docker compose up -d

    # Give the containers a moment to settle.
    - name: wait a tick
      if: steps.db-cache.outputs.cache-hit != 'true'
      shell: bash
      run: sleep 10

    - name: populate the site
      if: steps.db-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cp web/sites/example.settings.dev.php web/sites/settings.dev.php
        make install-site
        make load-spatial
        make update-translations

    - name: dump database
      if: steps.db-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mysqldump \
          --host=127.0.0.1 \
          --port=3306 \
          --password=drupal \
          --user=root \
          --compact \
          --add-drop-table \
          --add-drop-trigger \
          weathergov > weathergov.sql
