runs:
  using: composite
  steps:
    - name: setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "8.2"

    - name: get composer paths
      id: composer-paths
      shell: bash
      run: |
        echo "cache-dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
        echo "bin-dir=${{ github.workspace }}/$(composer config bin-dir)" >> $GITHUB_OUTPUT

    - name: cache composer caches
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-paths.outputs.cache-dir }}
        key: composer-cache-${{ hashFiles('composer.lock') }}

    - name: install dependencies
      env:
        COMPOSER_NO_DEV: 0
      shell: bash
      run: composer install

    - name: run phpcs
      shell: bash
      run: |
        echo "::add-matcher::${{ github.workspace }}/.github/workflows/problem-matcher-phpcs.json"
        vendor/bin/phpcs --report=checkstyle