runs:
  using: composite
  strategy:
    fail-fast: false
    matrix:
      shardIndex: [1, 2, 3, 4]
      shardTotal: [4]
  steps:
    - uses: browser-actions/setup-chrome@v1
    - uses: browser-actions/setup-edge@v1
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: install dependencies
      shell: bash
      run: npm ci
    - name: install browsers
      shell: bash
      run: npx playwright install --with-deps
