runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: install dependencies
      shell: bash
      run: npm ci
    - name: install browsers
      shell: bash
      run: npx playwright install --with-deps
